theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: after-hero
  posts:
    index:
      layout: list
      show_categories: true
      truncate_description: 0
  pages:
    index:
      truncate_description: 0