theme: osuny-hugo-theme-aaa

params:
  breadcrumb:
    position: after-hero
  posts:
    index:
      layout: grid
      show_categories: true
      truncate_description: 0
  pages:
    index:
      truncate_description: 0