theme: osuny-hugo-theme-aaa

params:
  breadcrumb:
    position: after-hero
  posts:
    list:
      show_categories: true
      truncate_description: 0
  pages:
    list:
      truncate_description: 0